version: 2.1

executors:
  java-executor:
    docker:
      - image: cimg/openjdk:17.0

jobs:
  build:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Install tar (If Missing)
          command: |
            if ! command -v tar &> /dev/null; then
              echo "Installing tar..."
              apt-get update && apt-get install -y tar
            else
              echo "tar is already installed."
            fi
      - run: 
          name: Verify Code Exists
          command: ls -la
      - run:
          name: Build with Maven
          command: mvn clean package
      - persist_to_workspace:
          root: .
          paths:
            - target/demo-0.0.1-SNAPSHOT.jar

  docker-push:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          name: Authenticate to AWS
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region us-east-1
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/java-ecs-ci-cd:latest .
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com
            docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/java-ecs-ci-cd:latest

  deploy:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Deploy to ECS
          command: |
            aws ecs update-service --cluster java-cluster --service java-service --force-new-deployment

workflows:
  version: 2
  ci-cd:
    jobs:
      - build
      - docker-push:
          requires:
            - build
      - deploy:
          requires:
            - docker-push
