version: 2.1

executors:
  java-executor:
    docker:
      - image: eclipse-temurin:17-jdk  # Official Java 17 Image

jobs:
  build:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Install Required Packages (tar, gzip & Maven)
          command: |
            echo "Updating package lists..."
            apt-get update
            echo "Installing tar and gzip..."
            apt-get install -y tar gzip
            echo "Installing Maven..."
            apt-get install -y maven
            echo "Verifying installations..."
            tar --version
            gzip --version
            mvn -version
      - run:
          name: Verify Code Exists
          command: ls -la
      - run:
          name: Build with Maven
          command: mvn clean package
      - persist_to_workspace:
          root: .
          paths:
            - target/demo-0.0.1-SNAPSHOT.jar

  docker-push:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install tar, gzip and Docker
          command: |
            echo "Installing tar and gzip..."
            yum install -y tar gzip
            echo "Installing Docker..."
            yum install -y amazon-linux-extras
            amazon-linux-extras install -y docker
            # Start Docker daemon directly
            dockerd > /var/log/dockerd.log 2>&1 &
            # Wait for Docker to be ready
            sleep 10
            echo "Verifying installations..."
            tar --version
            gzip --version
            docker --version
            docker info
      - attach_workspace:
          at: .
      - run:
          name: Authenticate to AWS
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region us-east-1
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/java-ecs-ci-cd:latest .
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com
            docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/java-ecs-ci-cd:latest

  deploy:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Deploy to ECS
          command: |
            aws ecs update-service --cluster java-cluster --service java-service --force-new-deployment

workflows:
  version: 2
  ci-cd:
    jobs:
      - build
      - docker-push:
          requires:
            - build
      - deploy:
          requires:
            - docker-push
