version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.15
  aws-ecs: circleci/aws-ecs@2.2.0

jobs:
  build-and-push:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn clean package -DskipTests
      - aws-ecr/build-and-push-image:
          repo: hello-world-app
          tag: ${CIRCLE_SHA1}
          path: .
          dockerfile: Dockerfile

  deploy:
    docker:
      - image: cimg/aws-cli:2.0
    steps:
      - aws-ecs/deploy-service-update:
          family: hello-world-app
          cluster-name: hello-world-cluster
          container-image-name-updates: container=hello-world-app,tag=${CIRCLE_SHA1}

workflows:
  build-and-deploy:
    jobs:
      - build-and-push
      - deploy:
          requires:
            - build-and-push
          filters:
            branches:
              only: main 